name: CI/CD

# Només s'executa quan es fa push a main
on:
  push:
    branches: [main]

jobs:
  test:
    name: Build, Lint i Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codi
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instal·la dependències
        run: npm ci

      - name: Lint amb ESLint
        run: npm run lint

      - name: Tests amb Vitest
        run: npm test

  deploy:
    name: Deploy a Render
    needs: test
    if: success()  # Només si el job `test` ha passat
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via Deploy Hook
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
